[package]
name = "rust_hero"
version = "0.0.1"
authors = ["Neil Grattan"]

[dependencies]
winapi = "0.2"
user32-sys = "0.2"
kernel32-sys = "0.2"
gdi32-sys = "0.2"
libc = "0.2"
"libloading" = "0.4"
handmade = { path = "../handmade"}